### ISSUE TITLE
Open anki shows add-on failed to load

### ISSUE THREAD

**Issue by panmengguan** [hwiorn/anki-open-org-note#1]
![image](https://user-images.githubusercontent.com/4384206/212792101-9211a120-c2d2-4cca-b4f1-e833d367c7f0.png)

After installing this add-on, re-opening the anki shows the above error message. My anki version is 2.1.11 (windows 10).

Thanks!

**Comment by hwiorn** [comment]
I updated the add-on to support the old Anki version(<2.1.20).
Before Anki 2.1.20, `gui_hooks` doesn't exist. I changed `gui_hooks` to `addHook (Legacy version)`.
You can use the 1.1.5(7420ef59d9c4b1272d24f603ffd32da4596a074e) version now. 
Click the update on the add-on dialog and restart your Anki.

However, I recommend you to use Anki 2.1.45 at least.
Many anki add-ons(e.g. anki-connect) need the latest Anki.

**Comment by panmengguan** [comment]
Thanks! And thank you for the suggestion. My anki version is really too old. But anki-connect works in this version. I keep this version since it is compatible with my Ankidroid and ankihelper (https://github.com/mmjang/ankihelper) apps on my Android phone.

**Comment by hwiorn** [comment]
The Ankidroid and ankihelper are Android apps. The ankihelper uses the Ankidroid. Ankidroid doesn't matter what Anki version is. I think, Ankidroid would require latest Anki version rather.  I can't find any dependency to specific Anki version. Just out of curiousity, do you use any other add-ons for Anki 2.1.11?

**Comment by panmengguan** [comment]
> The Ankidroid and ankihelper are Android apps. The ankihelper uses the Ankidroid. Ankidroid doesn't matter what Anki version is. I think, Ankidroid would require latest Anki version rather. I can't find any dependency to specific Anki version. Just out of curiousity, do you use any other add-ons for Anki 2.1.11?

My work and reading flow rely heavily on the ankiconnect and fastwq addons of Anki, both work fine for Anki 2.1.11. I will try `open-org-note` these days and maybe it will become one of my frequent used addons 😊. Other addons include `review heatmap`, `batch editing` (https://ankiweb.net/shared/info/291119185), etc. I also use the emacs `anki-editor`, `anki-vocabulary`, and `org-anki` packages to create Anki cards, all of them use the ankiconnect. 

![image](https://user-images.githubusercontent.com/4384206/213200434-cb307790-cfdb-4111-bd37-542da76136ca.png)

Actually, I have never updated my Anki since I used it for the first time and after spending all these time adapted to these various apps, addons, and emacs packages, I am afraid that the updating of one of them might break down their interactions. Especially the ankihelper app, it has not been updated for a long time. I cannot ascertain that it is compatible with the newest AnkiDroid app.

**Comment by hwiorn** [comment]
> My work and reading flow rely heavily on the ankiconnect and fastwq addons of Anki, both work fine for Anki 2.1.11. I will try open-org-note these days and maybe it will become one of my frequent used addons blush. Other addons include review heatmap, batch editing (https://ankiweb.net/shared/info/291119185), etc. I also use the emacs anki-editor, anki-vocabulary, and org-anki packages to create Anki cards, all of them use the ankiconnect.

I am interested in improving my reading and studying workflow. ankihelper seems to be fascinating. Unfortunately, I can't use the app because I'm Korean. I didn't even know anki-vocabulary exists.

> Actually, I have never updated my Anki since I used it for the first time and after spending all these time adapted to these various apps, addons, and emacs packages, I am afraid that the updating of one of them might break down their interactions. Especially the ankihelper app, it has not been updated for a long time. I cannot ascertain that it is compatible with the newest AnkiDroid app.

I understand what you mean. I struggled with over 20 add-ons and the latest Anki version a few years ago. Glutanimate's add-ons are mostly unusable in Anki 2.1. After learning a few lessons, I only keep a few add-ons which I think really help me.

Thanks for your kind reply :)

**Comment by panmengguan** [comment]
> > My work and reading flow rely heavily on the ankiconnect and fastwq addons of Anki, both work fine for Anki 2.1.11. I will try open-org-note these days and maybe it will become one of my frequent used addons blush. Other addons include review heatmap, batch editing (https://ankiweb.net/shared/info/291119185), etc. I also use the emacs anki-editor, anki-vocabulary, and org-anki packages to create Anki cards, all of them use the ankiconnect.
> 
> I am interested in improving my reading and studying workflow. ankihelper seems to be fascinating. Unfortunately, I can't use the app because I'm Korean. I didn't even know anki-vocabulary exists.
> 
> > Actually, I have never updated my Anki since I used it for the first time and after spending all these time adapted to these various apps, addons, and emacs packages, I am afraid that the updating of one of them might break down their interactions. Especially the ankihelper app, it has not been updated for a long time. I cannot ascertain that it is compatible with the newest AnkiDroid app.
> 
> I understand what you mean. I struggled with over 20 add-ons and the latest Anki version a few years ago. Glutanimate's add-ons are mostly unusable in Anki 2.1. After learning a few lessons, I only keep a few add-ons which I think really help me.
> 
> Thanks for your kind reply :)

I also want to thank you for this add-on and your reply. I learned a lot from them. Thanks!
