### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by browneyedsoul** [hwiorn/anki-open-org-note#2]
Hey! Happy Thanksgiving holiday! I really appreciate your amazing work! I just want to know if this plugin is available on macOS. I tried, but I couldn't find the ID in Emacs.

![q9Vd6Nps-h8u1MpZr-defNwMXY-y1ozMFnA-9GDWeJKu](https://github.com/hwiorn/anki-open-org-note/assets/56161102/95b6ad79-fb46-43c8-89d6-c44a899d246f)

Thanks!

**Comment by hwiorn** [comment]
This plugin is already compatible with macOS. 
My main laptops are MBP(2013 late and M2 pro) and LG GRAM(Manjaro linux). So, It should work without any error.

It seems that you didn't restart the Anki. I think this issue will be occurred after the plugin is installed at first.

If you still have the issue, I need more information. 
- macOS version
- Ripgrep version
- Anki version
- plugin log (go to the Anki.app and MacOS directory and run the ./anki from terminal)
- etc.

**Comment by browneyedsoul** [comment]
After debugging, I realized the issue was that I hadn't initiated the server in Emacs (M-x start-server). 
It might be helpful to add this information to the README file. Thank you very much!

Best,

**Comment by hwiorn** [comment]
> It might be helpful to add this information to the README file. Thank you very much!

Thank you for your suggestion :)
I will update the README.

**Comment by opsnull** [comment]
@hwiorn  same problem here，maybe related to regexp：
```
zj@a:~$ cd /Applications/Anki.app/Contents/
CodeResources   Frameworks/     Info.plist      MacOS/          Resources/      _CodeSignature/ 
zj@a:~$ cd /Applications/Anki.app/Contents/MacOS/
zj@a:/Applications/Anki.app/Contents/MacOS$ ls
anki*  lib/  libankihelper.dylib
zj@a:/Applications/Anki.app/Contents/MacOS$ ./anki 
Anki starting...
Initial setup...
Preparing to run...
Qt debug: doh set to ""  --  SystemOnly 
Starting main loop...
JS warning /_anki/js/editor.js:438 No version information available for component [tex]/noerrors
JS warning /_anki/js/editor.js:438 No version information available for component [tex]/mathtools
JS warning /_anki/js/editor.js:438 No version information available for component [tex]/mhchem
regex parse error:
    ^\s*(?:#\+|:)(ANKI_NOTE_ID|ATTR_ID):\s*\"?1703514630494\"?\b
                                           ^^
error: unrecognized escape sequence
regex parse error:
    ^\s*(?:#\+|:)(ANKI_NOTE_ID|ATTR_ID):\s*\"?1703514630494\"?\b
                                           ^^
error: unrecognized escape sequence
regex parse error:
    ^\s*(?:#\+|:)(ANKI_NOTE_ID|ATTR_ID):\s*\"?1703514630494\"?\b
```

**Comment by hwiorn** [comment]
Hm... Okay, I fixed it. Try 1.1.7 version.
Thank you for the reporting. I found an encoding issue here and fixed it though.
