### ISSUE TITLE
'list' object has no attribute 'split'

### ISSUE THREAD

**Issue by colawithsauce** [hwiorn/anki-open-org-note#4]
Installed this plugin today, and followed the manual, finish config this add on:
```
{
    "org-paths": [
        "~/Org/roam"
    ],
    "ripgrep_opts": "rg -ni",
}
```

then I got error: 'list' object has no attribute 'split'. And I follow the Error Message and modify the code on L98 of `__init__.py`:

https://github.com/hwiorn/anki-open-org-note/blob/main/__init__.py#L98

into this:

```python
        rg_ret = subprocess.run(rg_opts + ['--json', pat, search_path], stdout=subprocess.PIPE).stdout.decode('utf-8')
```

and it works for me. 

I do not PR this because I can't figure out this is an unintentionally introduced BUG, or a compatible problem.

**Comment by colawithsauce** [comment]
To people may have same issue as me: 
1. Open `Tools` > `Addons` > click `Open Org Note` > click `view files` on right bottom.
2. Change L98 into I pasted above, save. 
3. Restart Anki

**Comment by hwiorn** [comment]
Thank you for the report. 
I checked ripgrep can't work anymore. This bug embarrassed me because Ripgrep is my first option in the plugin.

I'll fix this as soon as possible.

**Comment by hwiorn** [comment]
I updated to 1.1.6.
Try `Check for Updates` in Add-ons menu.
